export {default as _4pda} from './4pda.js';
export {default as _5play} from './5play.js';
export {default as apkpure} from './apkpure.js';
export {default as direct} from './direct.js';
export {default as fdroid} from './fdroid.js';
export {default as github} from './github.js';
export {default as gitlab} from './gitlab.js';
export {default as parse} from './parse.js';
export {default as tinkoff} from './tinkoff.js';
