name: SSH

on:
  push:
    branches:
      - master

jobs:
  ssh-vds:
    environment: vds
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        env:
          AAPKS_4PDA_MEMBER_ID: ${{ secrets.AAPKS_4PDA_MEMBER_ID }}
          AAPKS_4PDA_PASS_HASH: ${{ secrets.AAPKS_4PDA_PASS_HASH }}
          AAPKS_GITHUB_TOKEN: ${{ secrets.AAPKS_GITHUB_TOKEN }}
          AAPKS_DOMAIN: ${{ secrets.AAPKS_DOMAIN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: AAPKS_4PDA_MEMBER_ID,AAPKS_4PDA_PASS_HASH,AAPKS_GITHUB_TOKEN,AAPKS_DOMAIN
          script: |
            set -x
            lsb_release -a
            cd ~/git/android-apks
            git reset --hard
            git pull
            ~/.nvm/nvm-exec npm run setup
            systemctl restart android-apks.service
            ~/.nvm/nvm-exec npm run apk:dl
